language: python
python: 
- "3.6"
- "3.7"
- "3.8"
# command to install dependencies
install: 
- curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
- source $HOME/.poetry/env
- cd DatosDemograficos; poetry install
- cd DatosDemograficos; poetry update
# command to run tests
script:
- cd DatosDemograficos; poetry run task coverage 
- cd DatosDemograficos; poetry run task test_int 
#Codecov
after_success:
- bash <(curl -s https://codecov.io/bash)
